Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "yeejinS2" do |server|
    server.vm.hostname = "yeejinS2"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.provider "virtualbox" do |v|
      v.name = "yeejinS2"
      v.cpus = 1
      v.memory = 1024
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end
end
